### ISSUE TITLE
Toggles have zero width on Linux/Proton

### ISSUE THREAD

**Issue by aelis440** [SolastaMods/SolastaModApi#44]
I've yet to determine exactly why, however running on Linux/Proton, Toggle components render with zero width, making them unclickable.  Example: https://ibb.co/dgBPy9K

As a quick fix, I replaced the unicode character with ON/OFF text and everything works great: https://ibb.co/t87SvJP

I can't seem to make a PR to this repo, so I'm attaching the patch below, it's fairly straightforward.
```
diff --git a/SolastaModApi/ModKit/UI/UI+Elements.cs b/SolastaModApi/ModKit/UI/UI+Elements.cs
index 1b9992f..7ce18b6 100644
--- a/SolastaModApi/ModKit/UI/UI+Elements.cs
+++ b/SolastaModApi/ModKit/UI/UI+Elements.cs
@@ -4,8 +4,8 @@ using UnityEngine;
 namespace ModKit {
     public static partial class UI {
 
-        public const string ChecklyphOn = "<color=green><b>✔</b></color>";
-        public const string CheckGlyphOff = "<color=#B8B8B8FF>✖</color>";      // #A0A0A0E0
+        public const string ChecklyphOn = "<color=green><b>ON</b></color>";
+        public const string CheckGlyphOff = "<color=#B8B8B8FF>OFF</color>";      // #A0A0A0E0
         public const string CheckGlyphEmpty = " <color=#B8B8B8FF>▪</color> ";
         public const string DisclosureGlyphOn = "<color=orange><b>▼</b></color>";      // ▼▲∧⋀
         public const string DisclosureGlyphOff = "<color=#C0C0C0FF><b>▶</b></color>";  // ▶▲∨⋁
```

**Comment by ThyWoof** [comment]
How about the triangle toggles on Game UI? Do they render fine on Linux?

**Comment by ThyWoof** [comment]
What I’m considering doing is having a setting we can change in ModApi xml file to enable these

**Comment by aelis440** [comment]
That's probably a good idea, the others seem to work fine, but I believe they're being used with a fixed height/width, e.g https://github.com/ChrisPJohn/SolastaCommunityExpansion/blob/Dev/SolastaCommunityExpansion/Viewers/Displays/CharacterDisplay.cs#L123

On their own, my guess is they'd also have a zero width.  I tried to find a way to detect if the user is on Linux, but with Proton that's a little tricky. : P

**Comment by ThyWoof** [comment]
before we change the code can you check if ```sudo apt install ttf-mscorefonts-installer
sudo fc-cache -f``` does the trick?

**Comment by aelis440** [comment]
Doesn't seem to have helped, I tried installing that directly as well as copying the new fonts directly into the wine prefix and neither worked.

**Comment by ThyWoof** [comment]
fixed.

**Comment by aelis440** [comment]
Awesome, thank you @ThyWoof!
